<?php
/**
 * Flow: Fetch user table (local) → สร้างคำสั่ง UPDATE SQL → คัดลอกไฟล์ไปรันบน server เพื่ออัปเดต user table บน server
 *
 * 1. ดึงข้อมูลจากตาราง user ในฐานข้อมูล local
 * 2. สร้างไฟล์ SQL ที่มีคำสั่ง UPDATE user SET ... WHERE email = '...' สำหรับแต่ละแถว
 * 3. นำไฟล์ไปวางบน server แล้วรัน: mysql -u user -p database < update_user_from_local.sql
 *
 * Usage: php scripts/generate_user_update_sql_from_local.php [--output=path]
 *
 * กำหนดค่า DB local ใน .env (database.default.*) หรือใช้ค่าเริ่มต้น localhost/root/''/newscience
 */

$projectRoot = dirname(__DIR__);
$envFile = $projectRoot . DIRECTORY_SEPARATOR . '.env';

function parseEnvDefaultDb(string $envFile): array
{
    $config = [
        'hostname' => 'localhost',
        'database' => 'newscience',
        'username' => 'root',
        'password' => '',
        'port'     => 3306,
    ];
    if (!is_file($envFile) || !is_readable($envFile)) {
        return $config;
    }
    $prefix = 'database.default.';
    $lines = @file($envFile, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES) ?: [];
    foreach ($lines as $line) {
        $line = trim($line);
        if ($line === '' || $line[0] === '#') {
            continue;
        }
        if (strpos($line, '=') === false) {
            continue;
        }
        [$key, $value] = explode('=', $line, 2);
        $key = trim($key);
        $value = trim($value, " \t\"'");
        if (stripos($key, $prefix) !== 0) {
            continue;
        }
        $k = strtolower(str_replace($prefix, '', $key));
        if ($k === 'hostname') {
            $config['hostname'] = $value;
        } elseif ($k === 'database') {
            $config['database'] = $value;
        } elseif ($k === 'username') {
            $config['username'] = $value;
        } elseif ($k === 'password') {
            $config['password'] = $value;
        } elseif ($k === 'port') {
            $config['port'] = (int) $value ?: 3306;
        }
    }
    return $config;
}

function sqlEscape($value): string
{
    if ($value === null || $value === '') {
        return '';
    }
    return str_replace("'", "''", (string) $value);
}

$config = parseEnvDefaultDb($envFile);
$conn = @new mysqli(
    $config['hostname'],
    $config['username'],
    $config['password'],
    $config['database'],
    $config['port']
);
if ($conn->connect_error) {
    fwrite(STDERR, "Local DB connection failed: " . $conn->connect_error . "\n");
    exit(1);
}
$conn->set_charset('utf8mb4');

// คอลัมน์ที่ต้องการ sync ไป server (ใช้ email เป็น key ใน WHERE) — เฉพาะที่มีในตาราง
$wantedColumns = [
    'login_uid',
    'title',
    'gf_name',
    'gl_name',
    'tf_name',
    'tl_name',
    'role',
    'status',
    'active',
];
$existingCols = [];
$r = $conn->query("SHOW COLUMNS FROM `user`");
while ($c = $r->fetch_assoc()) {
    $existingCols[] = $c['Field'];
}
$columns = array_intersect($wantedColumns, $existingCols);
$selectCols = array_merge(['email'], $columns);
$colList = implode(', ', array_map(function ($c) {
    return "`$c`";
}, $selectCols));

$res = $conn->query("SELECT {$colList} FROM `user` ORDER BY email");
if (!$res) {
    fwrite(STDERR, "Query failed: " . $conn->error . "\n");
    exit(1);
}

$outputPath = $projectRoot . DIRECTORY_SEPARATOR . 'database' . DIRECTORY_SEPARATOR . 'update_user_from_local.sql';
foreach ($GLOBALS['argv'] ?? [] as $arg) {
    if (strpos($arg, '--output=') === 0) {
        $outputPath = substr($arg, 9);
        break;
    }
}

$lines = [
    '-- =============================================================================',
    '-- Generated by scripts/generate_user_update_sql_from_local.php',
    '-- อัปเดตตาราง user บน SERVER จากข้อมูล local (จับคู่ด้วย email)',
    '-- รันบน server: mysql -u USER -p DATABASE < update_user_from_local.sql',
    '-- =============================================================================',
    '',
    'SET NAMES utf8mb4;',
    '',
];

$count = 0;
while ($row = $res->fetch_assoc()) {
    $email = trim($row['email'] ?? '');
    if ($email === '') {
        continue;
    }
    $emailEsc = sqlEscape($email);
    $sets = [];
    foreach ($columns as $col) {
        $val = $row[$col] ?? null;
        if ($val === null || (is_string($val) && trim($val) === '')) {
            $sets[] = "`{$col}` = NULL";
        } else {
            $sets[] = "`{$col}` = '" . sqlEscape($val) . "'";
        }
    }
    $lines[] = "UPDATE `user` SET " . implode(', ', $sets) . " WHERE `email` = '{$emailEsc}';";
    $count++;
}

$conn->close();

$sql = implode("\n", $lines);
$dir = dirname($outputPath);
if (!is_dir($dir)) {
    @mkdir($dir, 0755, true);
}
if (file_put_contents($outputPath, $sql) === false) {
    fwrite(STDERR, "Failed to write: " . $outputPath . "\n");
    exit(1);
}

echo "Generated " . $count . " UPDATE statement(s).\n";
echo "Output: " . $outputPath . "\n";
echo "\nCopy this file to the server and run:\n";
echo "  mysql -u USER -p DATABASE < update_user_from_local.sql\n";
echo "Or paste the SQL into phpMyAdmin / MySQL client on the server.\n";
